actor1:
  - [-4, 11.1]
  - [4, 11.1]
  - [4, 2]
  - [4, 11]
# actor2:
#   - [4.5, -10]
#   - [4.5, 1.0]
actor2:
  - [5.0, -8]
  - [5.0, 1]
actor3:
  - [5.0, 1.0]
  - [5.0, -9.0]
actor4:
  - [5.0, 13.0]
  - [-5.0, 13.0]
actor5:
  - [10.5, 4.5]
  - [4.5, 4.5]
  - [0.0, 10.0]
  - [4.5, 4.5]
actor6:
  - [5.0, -22.5]
  - [5.0, 13.5]
actor7:
  - [5.0, -11.5]
  - [5.0, -26.0]
# actor9:
#   - [5.5, 10.5]
#   - [-5.5, 10.5]
actor8:
  - [5.5, 10.9]
  - [-5.5, 10.9]
